# Generated by Django 3.1.2 on 2020-10-14 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='1900-01-01', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='race',
            field=models.CharField(choices=[('A', 'Asian'), ('B', 'Black'), ('I', 'Indian'), ('L', 'Latino'), ('M', 'Middle Eastern'), ('W', 'White')], default='W', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
