# Generated by Django 3.1.2 on 2020-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20201014_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[(
                'F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='race',
            field=models.CharField(blank=True, choices=[('A', 'Asian'), (
                'B', 'Black'), ('I', 'Indian'), ('L', 'Latino'), (
                    'M', 'Middle Eastern'), ('W', 'White')],
                max_length=1, null=True
            ),
        ),
    ]
