# Generated by Django 3.1.2 on 2020-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_links_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(default='Ranczo', max_length=255),
            preserve_default=False,
        ),
    ]
