# Generated by Django 3.1.2 on 2020-10-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20201016_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='persons.person'),
        ),
    ]
