# Generated by Django 3.1.2 on 2020-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20201016_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='person',
            field=models.ManyToManyField(related_name='movies', to='persons.Person'),
        ),
    ]
